---
- hosts: all
  tasks:
    - name: install require packages
      become: yes
      apt:
        name:
          - xserver-xorg
          - xserver-xorg-legacy
          - xserver-xorg-input-libinput
          - xserver-xorg-video-fbturbo
          - x11-xserver-utils
          - xinput-calibrator
          - xfonts-scalable
          - xfonts-100dpi
          - xfonts-75dpi
          - xfonts-base
          - xinit
          - awesome
          - midori
          - chromium-browser
          - gmpc
          - iok
        state: present

    - name: allow all users to start X11
      become: yes
      lineinfile:
        path: /etc/X11/Xwrapper.config
        regexp: '^allowed_users='
        line: 'allowed_users=anybody'

    - name: create xorg.conf.d directory
      become: yes
      file:
        path: /etc/X11/xorg.conf.d
        state: directory

    - name: create 99-calibration.conf
      become: yes
      copy:
        src: files/99-calibration.conf
        dest: "/etc/X11/xorg.conf.d/99-calibration.conf"
      notify:
        - restart X11

    - name: place xinitrc
      copy:
        src: files/xinitrc
        dest: "{{ ansible_env.HOME }}/.xinitrc"
      notify:
        - restart X11

    - name: create .config/awesome dir
      file:
        path: "{{ ansible_env.HOME }}/.config/awesome/"
        state: directory
        recurse: yes

    - name: copy awesome configs
      copy:
        src: "files/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/awesome/{{ item }}"
      with_items:
        - rc.lua
        - theme.lua
      notify:
        - restart X11

    - name: start X11 direclty with systemd
      become: yes
      copy:
        src: files/xinit-login.service
        dest: /lib/systemd/system/xinit-login.service
      notify:
        - restart X11

    - name: enable and start systemd service
      become: yes
      systemd:
        name: xinit-login
        state: started
        enabled: yes
        masked: no
        daemon_reload: yes

  handlers:
    - name: restart X11
      become: yes
      systemd:
        name: xinit-login
        state: restarted
        daemon_reload: yes
